import { Geist, Geist_Mono, Jost } from "next/font/google";
import "./globals.css";

const jost = Jost({subsets:["latin"]}) ;

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Coffee Shop",
  description: "Generated by create next app",
};
import AOS from "aos";
import "aos/dist/aos.css";
// AOS.init();
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={jost.className}
      >
        {children}
      </body>
    </html>
  );
}
